# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
    version: v1
spec:
  type: NodePort
#  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: portal
    version: v1
