# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
      version: v1
  template:
    metadata:
      labels:
        app: portal
        version: v1
    spec:
      containers:
      - name: forecast
        image: portal:01
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
