# 只开发前端的话，portal本地起。node_modules挂volume性能过差。
version: "3"
services:
  portal:
    build:
      context: ../portal
      dockerfile: .prodcontainer/Dockerfile
    container_name: meta-portal
    restart: always
    ports:
      - '8000:8000'
  server-gin:
    build:
      context: ../server/gin
      dockerfile: .prodcontainer/Dockerfile
    container_name: meta-server-gin
    restart: always
    ports:
      - '8001:8001'
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
  server-toy:
    build:
      context: ../server/toy
      dockerfile: .prodcontainer/Dockerfile
    container_name: meta-server-toy
    restart: always
    ports:
      - '8002:8002'
  mysql:
    image: mysql:8.0
    container_name: meta-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "3306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'MCdev' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'mc@123' # root管理员用户密码
  redis:
    image: redis:7.0-rc-bullseye
    container_name: meta-redis 
    restart: always
    ports:
      - '6379:6379'