# 全部是dev容器，随时启动vscode，并open in container，在内置terminal里，重编译，重新起新进程。
version: "3"
services:
  dev-portal:
    build:
      context: ../portal
      dockerfile: .devcontainer/Dockerfile
      args: { "VARIANT": "16-bullseye" }
    container_name: meta-dev-portal
    restart: always
    volumes:
      - ../:/workspaces:cached
    ports:
      - '8000:8000'
    command:
      - /bin/sh
      - -c
      - |
        npm i -g pnpm
        pnpm install
        pnpm dev

  dev-server-gin:
    build:
      context: ../server/gin
      dockerfile: .devcontainer/Dockerfile
      args: {"VARIANT": "1.17-bullseye","NODE_VERSION": "lts/*"}
    container_name: meta-dev-server-gin
    restart: always
    volumes:
      - ../:/workspaces:cached
    ports:
      - '8001:8001'
    depends_on:
      - dev-mysql
      - dev-redis
    links:
      - dev-mysql
      - dev-redis
    command: 
      - /bin/sh
      - -c
      - |
        go build server.go 
        ./server
  dev-server-toy:
    build:
      context: ../server/toy
      dockerfile: .devcontainer/Dockerfile
      args: { "VARIANT": "3.9-bullseye","NODE_VERSION": "lts/*"}
    container_name: meta-dev-server-toy
    restart: always
    volumes:
      # Mount the root folder that contains .git
      - ../:/workspaces:cached
    ports:
      - '8002:8002'
    command: 
      - /bin/sh
      - -c
      - |
        pip3 install -r requirements.txt
        python app.py
  dev-mysql:
    image: mysql:8.0
    container_name: meta-dev-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "3306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'MCdev' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'mc@123' # root管理员用户密码
  dev-redis:
    image: redis:7.0-rc-bullseye
    container_name: meta-dev-redis 
    restart: always
    ports:
      - '6379:6379'