version: "3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '192.168.0.0/16'

services:
  portal:
    build:
      context: ./portal
      dockerfile: ./prodcontainer/Dockerfile
    container_name: meta-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 192.168.0.21

  server:
    build:
      context: ./server
      dockerfile: ./prodcontainer/Dockerfile
    container_name: meta-server
    restart: always
    ports:
      - '9000:9000'
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 192.168.0.22

  mysql:
    image: mysql:8.0.21
    container_name: meta-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'qmPlus' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'Aa@6447985' # root管理员用户密码
    networks:
      network:
        ipv4_address: 192.168.0.23

  redis:
    image: redis:6.0.6
    container_name: meta-redis # 容器名
    restart: always
    ports:
      - '16379:6379'
    networks:
      network:
        ipv4_address: 192.168.0.24