# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gin
  labels:
    app: server-gin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-gin
      version: v1
  template:
    metadata:
      labels:
        app: server-gin
        version: v1
    spec:
      containers:
      - name: forecast
        image: server-gin:01
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
