apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
    version: v1
spec:
  type: NodePort
#  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: portal
    version: v1
---
# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/
apiVersion: v1
kind: Service
metadata:
  name: server-gin
  labels:
    app: server-gin
    version: v1
spec:
  # type: NodePort
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  selector:
    app: server-gin
    version: v1

---
apiVersion: v1
kind: Service
metadata:
  name: server-toy
  labels:
    app: server-toy
    version: v1
spec:
  type: ClusterIP
#  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  selector:
    app: server-toy
    version: v1



