# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/
apiVersion: v1
kind: Service
metadata:
  name: server-toy
  labels:
    app: server-toy
    version: v1
spec:
  type: ClusterIP
#  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  selector:
    app: server-toy
    version: v1
