apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
    version: v1
spec:
  type: {{ .Values.microservice.portal.type }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: portal
    version: v1
---
# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/
apiVersion: v1
kind: Service
metadata:
  name: server-gin
  labels:
    app: server-gin
    version: v1
spec:
  type: {{ .Values.microservice.server_gin.type }}
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  selector:
    app: server-gin
    version: v1

---
apiVersion: v1
kind: Service
metadata:
  name: server-toy
  labels:
    app: server-toy
    version: v1
spec:
  type: {{ .Values.microservice.server_toy.type }}
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  selector:
    app: server-toy
    version: v1

---

apiVersion: v1
kind: Service
metadata:
  name: meta-redis
  labels:
    app: meta-redis
    version: v1
spec:
  type: {{ .Values.microservice.meta_redis.type }}
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  selector:
    app: meta-redis
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: meta-mysql
  labels:
    app: meta-mysql
    version: v1
spec:
  type: {{ .Values.microservice.meta_mysql.type }}
  ports:
    - name: http
      port: 3306
      targetPort: 3306
  selector:
    app: meta-mysql
    version: v1
---


